DiabetesTrackerASPAplikacija/DiabetesTrackerASPAplikacija/Models/Podsjetnik.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DiabetesTrackerASPAplikacija.Models
{
    public class Podsjetnik
    {
        TipPodsjetnika tip;
        DateTime datum;
        Ponavljanja ponavljanje;
        String opis;
        int id;
        [Required]
        [DisplayName ("Tip podsjetnika")]
        public TipPodsjetnika Tip { get => tip; set => tip = value; }
        [Required]
        public DateTime Datum { get => datum; set => datum = value; }
        [Required]
        public Ponavljanja Ponavljanje { get => ponavljanje; set => ponavljanje = value; }
        [Required]
        public string Opis { get => opis; set => opis = value; }
        public int Id { get => id; set => id = value; }

        public int KorisnikId { get; set; }

        public virtual Korisnik Korisnik { get; set; }
    }
}

DiabetesTrackerASPAplikacija/DiabetesTrackerASPAplikacija/Controllers/PodsjetniksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DiabetesTrackerASPAplikacija.Models;

namespace DiabetesTrackerASPAplikacija.Controllers
{
    [Authorize]
    public class PodsjetniksController : Controller
    {
        
        private DiabetesTrackerASPAplikacijaContext db = new DiabetesTrackerASPAplikacijaContext();

        // GET: Podsjetniks
        public ActionResult Index()
        {
            var podsjetnik = db.Podsjetnik.Include(p => p.Korisnik);
            return View(podsjetnik.ToList());
        }

        // GET: Podsjetniks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Podsjetnik podsjetnik = db.Podsjetnik.Find(id);
            if (podsjetnik == null)
            {
                return HttpNotFound();
            }
            return View(podsjetnik);
        }

        // GET: Podsjetniks/Create
        public ActionResult Create()
        {
            ViewBag.KorisnikId = new SelectList(db.Korisnik, "Id", "TipDijabetesa");
            return View();
        }

        // POST: Podsjetniks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Tip,Datum,Ponavljanje,Opis,KorisnikId")] Podsjetnik podsjetnik)
        {
            if (ModelState.IsValid)
            {
                var dajId = db.Database.SqlQuery<int>("SELECT Id FROM dbo.Korisnik WHERE " + "EMail = '" + User.Identity.Name + "'").ToList();
                if (dajId.Count > 0)
                    podsjetnik.KorisnikId = dajId[0];                
                db.Podsjetnik.Add(podsjetnik);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }

            ViewBag.KorisnikId = new SelectList(db.Korisnik, "Id", "TipDijabetesa", podsjetnik.KorisnikId);
            return View(podsjetnik);
        }

        // GET: Podsjetniks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Podsjetnik podsjetnik = db.Podsjetnik.Find(id);
            if (podsjetnik == null)
            {
                return HttpNotFound();
            }
            ViewBag.KorisnikId = new SelectList(db.Korisnik, "Id", "TipDijabetesa", podsjetnik.KorisnikId);
            return View(podsjetnik);
        }

        // POST: Podsjetniks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Tip,Datum,Ponavljanje,Opis,KorisnikId")] Podsjetnik podsjetnik)
        {
            if (ModelState.IsValid)
            {
                db.Entry(podsjetnik).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KorisnikId = new SelectList(db.Korisnik, "Id", "TipDijabetesa", podsjetnik.KorisnikId);
            return View(podsjetnik);
        }

        // GET: Podsjetniks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Podsjetnik podsjetnik = db.Podsjetnik.Find(id);
            if (podsjetnik == null)
            {
                return HttpNotFound();
            }
            return View(podsjetnik);
        }

        // POST: Podsjetniks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Podsjetnik podsjetnik = db.Podsjetnik.Find(id);
            db.Podsjetnik.Remove(podsjetnik);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

DiabetesTrackerASPAplikacija/DiabetesTrackerASPAplikacija/Views/Podsjetniks/Create.cshtml
@model DiabetesTrackerASPAplikacija.Models.Podsjetnik

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Podsjetnik</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Tip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Tip, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Tip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Datum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Datum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Datum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ponavljanje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Ponavljanje, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Ponavljanje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--
        <div class="form-group">
            @Html.LabelFor(model => model.KorisnikId, "KorisnikId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KorisnikId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KorisnikId, "", new { @class = "text-danger" })
            </div>
        </div>
            -->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Pregledaj kreirani podsjetnik", "Details", "Podsjetniks")
        @Html.ActionLink("Back to List", "Index")
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DiabetesTrackerASPAplikacija/DiabetesTrackerASPAplikacija/Views/Podsjetniks/Delete.cshtml
@model DiabetesTrackerASPAplikacija.Models.Podsjetnik

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Podsjetnik</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Korisnik.TipDijabetesa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Korisnik.TipDijabetesa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Datum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Datum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ponavljanje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ponavljanje)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DiabetesTrackerASPAplikacija/DiabetesTrackerASPAplikacija/Views/Podsjetniks/Details.cshtml
@model DiabetesTrackerASPAplikacija.Models.Podsjetnik

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Podsjetnik</h4>
    <hr />
    <dl class="dl-horizontal">
        @{ /*var db = new DiabetesTrackerASPAplikacija.Models.DiabetesTrackerASPAplikacijaContext();
            var dajPodsjetnike = db.Database.SqlQuery<int>("SELECT Podsjetnik.Id FROM dbo.Korisnik, dbo.Podsjetnik WHERE " + "dbo.Korisnik.EMail = '" + User.Identity.Name + "' AND dbo.Korisnik.Id=dbo.Podsjetnik.KorisnikId" ).ToList();
            if (dajPodsjetnike.Count != 0)
            {

                <li>@Html.ActionLink("Profil", "Index", "Korisniks/Details/" + dajPodsjetnike[0])</li>
            }
            else
            {
                < li > @Html.ActionLink("Kreiraj profil", "Create", "Korisniks") </ li >
            }*/
        <dt>
            @Html.DisplayNameFor(model => model.Korisnik.TipDijabetesa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Korisnik.TipDijabetesa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Datum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Datum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ponavljanje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ponavljanje)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>
            }
    </dl>
            
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DiabetesTrackerASPAplikacija/DiabetesTrackerASPAplikacija/Views/Podsjetniks/Edit.cshtml
@model DiabetesTrackerASPAplikacija.Models.Podsjetnik

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Podsjetnik</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Tip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Tip, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Tip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Datum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Datum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Datum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ponavljanje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Ponavljanje, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Ponavljanje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KorisnikId, "KorisnikId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KorisnikId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KorisnikId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DiabetesTrackerASPAplikacija/DiabetesTrackerASPAplikacija/Views/Podsjetniks/Index.cshtml
@model IEnumerable<DiabetesTrackerASPAplikacija.Models.Podsjetnik>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <!--
        <th>
            @Html.DisplayNameFor(model => model.Korisnik.TipDijabetesa)
        </th>
            -->
        <th>
            @Html.DisplayNameFor(model => model.Tip)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Datum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ponavljanje)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Opis)
        </th>
        <th></th>
    </tr>

    @{
        {
            var db = new DiabetesTrackerASPAplikacija.Models.DiabetesTrackerASPAplikacijaContext();
            var dajPodsjetnike = db.Database.SqlQuery<DiabetesTrackerASPAplikacija.Models.Podsjetnik>("SELECT * FROM dbo.Podsjetnik, dbo.Korisnik WHERE " + "dbo.Korisnik.EMail = '" + User.Identity.Name + "' AND dbo.Korisnik.Id=dbo.Podsjetnik.KorisnikId").ToList();

            foreach (var item in dajPodsjetnike)
            {
            <tr>
                <!--
                <td>
                    @Html.DisplayFor(modelItem => item.Korisnik.TipDijabetesa)
                </td>
                    -->
                <td>
                    @Html.DisplayFor(modelItem => item.Tip)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Datum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ponavljanje)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Opis)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
                }
            }

        }
    </table>

DiabetesTrackerASPAplikacija/DiabetesTrackerASPAplikacija/Views/Podsjetniks/Prikaz.cshtml
@model DiabetesTrackerASPAplikacija.Models.Podsjetnik

@{
    ViewBag.Title = "Pregled podsjetnika";
}

<h2>Detalji</h2>

<div>
    <h4>Pregled podsjetnika</h4>
    <hr />
    <dl class="dl-horizontal">
        @{
            var db = new DiabetesTrackerASPAplikacija.Models.DiabetesTrackerASPAplikacijaContext();
            var dajPodsjetnike = db.Database.SqlQuery<DiabetesTrackerASPAplikacija.Models.Podsjetnik>("SELECT * FROM dbo.Podsjetnik, dbo.Korisnik WHERE " + "dbo.Korisnik.EMail = '" + User.Identity.Name + "' AND dbo.Korisnik.Id=dbo.Podsjetnik.KorisnikId").ToList();


            foreach (var m in dajPodsjetnike)
            {
                if (m.KorisnikId == Model.KorisnikId)
                {
                <dt>
                    @Html.DisplayNameFor(model => model.Tip)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Tip)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Datum)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Datum)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Ponavljanje)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Ponavljanje)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Opis)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Opis)
                </dd>
                    }
                }
            }
    </dl>


</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>